"""add created_at and storage_path to documents

Revision ID: bb2950df8057
Revises: eec4795a0846
Create Date: 2026-09-22 00:16:16.713471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb2950df8057'
down_revision: Union[str, None] = 'eec4795a0846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Adjusted from the raw autogenerate output: adding a NOT NULL
    # column with no default fails outright if the table already has
    # rows (there's nothing to put in the new column for them). A
    # server_default backfills existing rows, then gets dropped so it
    # doesn't linger and mask a real app-level bug on future inserts -
    # the ORM (Document model) always supplies both values itself.
    op.add_column(
        'documents',
        sa.Column('storage_path', sa.String(length=255), nullable=False, server_default=''),
    )
    op.add_column(
        'documents',
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    )
    op.alter_column('documents', 'storage_path', server_default=None)
    op.alter_column('documents', 'created_at', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'storage_path')
    # ### end Alembic commands ###
